{-
   Alertmanager API

   API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

   OpenAPI Version: 3.0.1
   Alertmanager API API version: 0.0.1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Alertmanager.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module Alertmanager.Logging
  ( module Alertmanager.LoggingKatip
  ) where

import Alertmanager.LoggingKatip

#else

module Alertmanager.Logging
  ( module Alertmanager.LoggingMonadLogger
  ) where

import Alertmanager.LoggingMonadLogger

#endif
