{-
   Alertmanager API

   API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

   OpenAPI Version: 3.0.1
   Alertmanager API API version: 0.0.1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Alertmanager.API.Alertgroup
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Alertmanager.API.Alertgroup where

import Alertmanager.Core
import Alertmanager.MimeTypes
import Alertmanager.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Alertgroup

-- *** getAlertGroups

-- | @GET \/alerts\/groups@
-- 
-- Get a list of alert groups
-- 
getAlertGroups 
  :: AlertmanagerRequest GetAlertGroups MimeNoContent [AlertGroup] MimeJSON
getAlertGroups =
  _mkRequest "GET" ["/alerts/groups"]

data GetAlertGroups  

-- | /Optional Param/ "active" - Show active alerts
instance HasOptionalParam GetAlertGroups Active where
  applyOptionalParam req (Active xs) =
    req `addQuery` toQuery ("active", Just xs)

-- | /Optional Param/ "silenced" - Show silenced alerts
instance HasOptionalParam GetAlertGroups Silenced where
  applyOptionalParam req (Silenced xs) =
    req `addQuery` toQuery ("silenced", Just xs)

-- | /Optional Param/ "inhibited" - Show inhibited alerts
instance HasOptionalParam GetAlertGroups Inhibited where
  applyOptionalParam req (Inhibited xs) =
    req `addQuery` toQuery ("inhibited", Just xs)

-- | /Optional Param/ "filter" - A list of matchers to filter alerts by
instance HasOptionalParam GetAlertGroups Filter where
  applyOptionalParam req (Filter xs) =
    req `addQuery` toQueryColl MultiParamArray ("filter", Just xs)

-- | /Optional Param/ "receiver" - A regex matching receivers to filter alerts by
instance HasOptionalParam GetAlertGroups Receiver2 where
  applyOptionalParam req (Receiver2 xs) =
    req `addQuery` toQuery ("receiver", Just xs)
-- | @application/json@
instance Produces GetAlertGroups MimeJSON

