{-
   Alertmanager API

   API of the Prometheus Alertmanager (https://github.com/prometheus/alertmanager)

   OpenAPI Version: 3.0.1
   Alertmanager API API version: 0.0.1
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Network.Alertmanager.OpenAPI.API
-}

module Network.Alertmanager.OpenAPI.API
  ( module Network.Alertmanager.OpenAPI.API.Alert
  , module Network.Alertmanager.OpenAPI.API.Alertgroup
  , module Network.Alertmanager.OpenAPI.API.General
  , module Network.Alertmanager.OpenAPI.API.Receiver
  , module Network.Alertmanager.OpenAPI.API.Silence
  ) where

import Network.Alertmanager.OpenAPI.API.Alert
import Network.Alertmanager.OpenAPI.API.Alertgroup
import Network.Alertmanager.OpenAPI.API.General
import Network.Alertmanager.OpenAPI.API.Receiver
import Network.Alertmanager.OpenAPI.API.Silence